#!/bin/bash

ESC="\033"
BLUE="${ESC}[34m"
RESET="${ESC}[0m"
WHITE="${ESC}[97m"
YELLOW="${ESC}[93m"
RED_BG="${ESC}[41m"
BLUE_BG="${ESC}[44m"
SEP="───────────────────────────────────────────"

echo -e "${BLUE}"
echo "                                                        "
echo "  ██████╗ ██████╗        ███╗   ██╗ █████╗ ███╗   ███╗███████╗"
echo " ██╔════╝██╔═══██╗       ████╗  ██║██╔══██╗████╗ ████║██╔════╝"
echo " ██║     ██║   ██║       ██╔██╗ ██║███████║██╔████╔██║█████╗  "
echo " ██║     ██║   ██║       ██║╚██╗██║██╔══██║██║╚██╔╝██║██╔══╝  "
echo " ╚██████╗╚██████╔╝██╗    ██║ ╚████║██║  ██║██║ ╚═╝ ██║███████╗"
echo "  ╚═════╝ ╚═════╝ ╚═╝    ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝"
echo -e "${RESET}"

if [ ! -d "./node_modules" ]; then
    echo -e " ${WHITE}${SEP}"
    echo -e "${BLUE}  Instalando dependências pela primeira vez...${RESET}"
    echo -e " ${SEP}"
    echo -e " ${YELLOW}${RED_BG}  Isso pode demorar alguns minutos. Aguarde...${RESET}"
    echo -e "  ${SEP}"
    ./bin/node ./bin/node_modules/npm/bin/npm-cli.js install
    echo -e "  ${SEP}"
fi

echo -e " ${WHITE}${SEP}"
echo -e "${BLUE}  Aguarde...${RESET}"
echo -e " ${SEP}"
echo -e " ${YELLOW}${RED_BG}  A primeira execução pode demorar..."
echo -e "  A permissão ao firewall é opcional${RESET}"
echo -e "  ${SEP}"
echo -e " ${BLUE_BG}"
./bin/node ./src/server.js
echo -e "${RESET}"

echo -e " ${RED_BG}${YELLOW}"
echo -e "  ${SEP}"
echo -e "  Encerrando..."
echo -e "  ${SEP}${RESET}"

CHOICE=$(( (RANDOM % 4) + 1 ))

case $CHOICE in
1)
    echo ""
    echo "             /\´¯/'   '/´¯¯\`·¸"
    echo "          /'/   /   /      /¨¯\\"
    echo "         ('(   \´   \´     ¯~/'  ')"
    echo "          \\                '    /"
    echo "           ''   \\          _.·\´"
    echo "            \\             ("
    echo ""
    echo "             Se você não fechar este terminal,"
    echo "                                  você não é brother..."
    echo ""
    ;;
2)
    echo ""
    echo "                      ,---.           ,---.          "
    echo "                     / /\"\`.\\.--\"\"\"--./,'\"\\ \\         "
    echo "                     \\ \\    _       _    / /         "
    echo "                      \`./  / __   __ \\  \\'          "
    echo "                       /    /_O)_(_O\\    \\           "
    echo "                       |  .-'  ___  \`-.  |          "
    echo "                    .--|       \\_/       |--.        "
    echo "                  ,'    \\   \\   |   /   /    \`.      "
    echo "                 /       \`.  \`--^--'  ,'       \\     "
    echo "              .-\"\"\"\"\"-.    \`--.___.--'     .-\"\"\"\"\"-.  "
    echo " .-----------/         \\------------------/         \\--------------."
    echo " | .---------\\         /----------------- \\         /------------. |"
    echo " | |          \`-\`--\`--'                    \`--'--'-'             | |"
    echo " | |                                                             | |"
    echo " | |   _,.-'~'-.,__,.-'~'-.,__,.-'~'-.,__,.-'~'-.,__,.-'~'-.,_   | |"
    echo " | |                O ursinho quer te dizer                      | |"
    echo " | |             que você já pode                                | |"
    echo " | |                       fechar este terminal :)               | |"
    echo " | |  _,.-'~'-.,__,.-'~'-.,__,.-'~'-.,__,.-'~'-.,__,.-'~'-.,_    | |"
    echo " | |_____________________________________________________________| |"
    echo " |_________________________________________________________________|"
    echo "                    )__________|__|__________("
    echo "                   |            ||            |"
    echo "                   |____________||____________|"
    echo "                     ),-----.(      ),-----.(  "
    echo "                   ,'   ==.   \\    /  .==    \`."
    echo "                  /            )  (            \\"
    echo "                  \`===========' \`===========' hjw"
    echo ""
    ;;
3)
    echo ""
    echo "                                     _"
    echo "   Este terminal você              ,:'/   _..._"
    echo "            já pode fechar        // ( \`\"\"-.._.' "
    echo "      e o doguinho então         \\| /    6\\___"
    echo "   levar para passear :)         |    6       4"
    echo "                                 |            /"
    echo "                                 \\_       .--'"
    echo "                                 (_'---'\`)"
    echo "                                 / \`'---\`()"
    echo "                               ,'        |"
    echo "               ,            .'\`          |"
    echo "               )\\       _.-'             ;"
    echo "              / |    .'\`   _            /"
    echo "            /\` /   .'       '.        , |"
    echo "           /  /   /           \\   ;   | |"
    echo "           |  \\  |            |  .|   | |"
    echo "            \\  \`\"|           /.-' |   | |"
    echo "             '-..-\\       _.;.._  |   |.;-."
    echo "                   \\    <\`.._ )) |  .;-. ))"
    echo "                   (__.  \`  ))-'  \\_    ))'"
    echo "                       \`'--\`\`  jgs  \`\"\"\"\`"
    echo ""
    ;;
4)
    echo ""
    echo "                   _....._"
    echo "               _.:'.--|--.':._"
    echo "             .: .'\o  | o /'. '."
    echo "            // '.  \\ o|  /  o '.\\"
    echo "           //'._ o'. \\ |o/ o_.-'o\\\\"
    echo "           || o '-.'.|/.-' o   ||"
    echo "           ||--o--o-->|"
    echo ""
    echo "               Chiudi questa finestra e"
    echo "                               goditi una fetta di pizza..."
    echo ""
    ;;
esac

read -r -p "  Pressione ENTER para fechar..."
